name: package/contracts - Build -> Test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  tests:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          yarn install
          cd packages/contracts
          yarn install

      - name: Compile Contract
        run: |
          yarn hh-compile
          
      - name: Test Contract
        run: |
          yarn hh-test

  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Get node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Run slither
        uses: crytic/slither-action@v0.1.1
        with:
          target: ./packages/hardhat
