name: package/contracts - Build -> Test
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          yarn install
          cd packages/contracts
          yarn install

      - name: Compile Contract
        run: |
          yarn hh-compile
          
      - name: Test Contract
        run: |
          yarn hh-test