name: package/grant-explorer - Build -> Test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    concurrency: ci-grant-explorer-${{ github.head_ref || github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: packages/grant-explorer/yarn.lock

      - name: Install Dependencies
        run: |
          yarn install
          cd packages/grant-explorer
          yarn install --frozen-lockfile

      - name: Build Grant Explorer
        run: |
          yarn re-build

      - name: Test Grant Explorer
        run: |
          yarn re-test
