name: packages/project-registry - Build -> Test

on:
  push:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Test and Build
      run: |
        cd packages/project-registry

        yarn install
        yarn lint
        yarn test
        yarn build
