name: package/round-manager - Build -> Test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          yarn install
          cd packages/round-manager
          yarn install

      - name: Build Round Manager
        run: |
          yarn rm-build
          
      - name: Test Round Manager
        run: |
          yarn rm-test