name: package/round-manager - Build -> Test -> Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          yarn install
          cd packages/round-manager
          yarn install

      - name: Build Round Manager
        run: |
          yarn rm-build
          
      - name: Test Round Manager
        run: |
          yarn rm-test
          
      - name: Deploy Round Manager
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/round-manager/build # The folder the action should deploy.
